#ifndef _ROBOTMAP_HG_
#define _ROBOTMAP_HG_

//Drive Train
const int DRIVETRAIN_RIGHT_FRONT_MOTOR_ID = 1;
const int DRIVETRAIN_RIGHT_REAR_MOTOR_ID = 2;
const int DRIVETRAIN_LEFT_FRONT_MOTOR_ID = 3;
const int DRIVETRAIN_LEFT_REAR_MOTOR_ID = 4;
const int DRIVETRAIN_LIFTER_MOTOR_ID = 5;
const int DRIVETRAIN_GRIPPER_WHEEL_MOTOR_ID = 6;
const int DRIVETRAIN_GRIPPER_ARMS_MOTOR_ID = 7;
const int DRIVETRAIN_WINCH_MOTOR_ID = 8;


const double WHEEL_RADIUS = 3.0;

//XBox Controller
const int XBOX_CONTROLLER_DRIVE_PORT = 0;
const int XBOX_CONTROLLER_OPERATOR_PORT = 1;
//controller deadzone
const double XBOX_DEADZONE_LEFT_JOY=0.1;
const double XBOX_DEADZONE_RIGHT_JOY=0.1;


#endif

